name: PR Label

on:
  pull_request_review:
    types: [submitted]

jobs:
  add-qa-label:
    runs-on: ubuntu-20.04
    if: ${{ github.event.review.state === 'approved' }}
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const prId = context.payload.pull_request.id

            const res = github.rest.pulls.listReviews({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: prId,
            });

            console.log('res', res)
