name: Retry Last PR Job

on:
  issue_comment:
    types: [created]

jobs:
  retry-last-pr-job:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'issue_comment' && contains(github.event.comment.body, 'retest this please') }}
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const prId = context.payload.issue.pull_request.url.split(`/pulls/`).pop()
            const repoName = context.payload.repository.name
            const repoOwner = context.payload.repository.owner.login

            if(!prId || !repoName || !repoOwner) {
              throw new Error(`Could not get prId: ${prId}, repName: ${repoName}, and/or repoOwner: ${repoOwner}`)
            }

            const getPullRequestResult = await github.rest.pulls.get({
              owner: repoOwner,
              repo: repoName,
              pull_number: prId,
            });

            const headSHA = getPullRequestResult.data.head.sha

            if(!headSHA) {
              throw new Error(`Could not get head SHA: ${headSHA}`)
            }

            const newCheckSuiteResult = await github.rest.checks.createSuite({
              owner: repoOwner,
              repo: repoName,
              head_sha: headSHA,
            });

            const newCheckSuiteId = newCheckSuiteResult.data.id

            github.rest.checks.rerequestSuite({
              owner: repoOwner,
              repo: repoName,
              check_suite_id: newCheckSuiteId,
            });
