name: Retry Last PR Job

on:
  issue_comment:
    types: [created]

jobs:
  retry-last-pr-job:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'issue_comment' && contains(github.event.comment.body, 'retest this please') }}
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            let prId = context.payload.issue.pull_request.url.split(`/pulls/`).pop()
            const repoName = context.payload.repository.name
            const repoOwner = context.payload.repository.owner.login

            prId = null
            if(!prId || !repoName || !repoOwner) {
              throw new Error(`Could not get prId: ${prId}, repName: ${repoName}, and/or repoOwner: ${repoOwner}`)
            }

            const getPullRequestResult = await github.rest.pulls.get({
              owner: repoOwner,
              repo: repoName,
              pull_number: prId,
            });

            const headSHA = getPullRequestResult.data.head.sha

            const getCheckSuitesResult = await github.rest.checks.listSuitesForRef({
              owner: repoOwner,
              repo: repoName,
              ref: headSHA,
            });

            const githubActionsCheckSuiteId = getCheckSuitesResult.data.check_suites.filter(suite => suite.app.slug === 'github-actions')[0].id

            const res = await github.rest.checks.rerequestSuite({
              owner: repoOwner,
              repo: repoName,
              check_suite_id: githubActionsCheckSuiteId,
            });

            console.log('res', res)
