name: Retry Last PR Job

on:
  issue_comment:
    types: [created]

jobs:
  retry-last-pr-job:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'issue_comment' && contains(github.event.comment.body, 'retest this please') }}
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const prId = context.payload.issue.pull_request.url.split(`/pulls/`).pop()
            const repoName = context.payload.repository.name
            const repoOwner = context.payload.repository.owner.login

            console.log({ prId, repoName, repoOwner })

            const getPullRequestResult = await github.rest.pulls.get({
              owner: repoOwner,
              repo: repoName,
              pull_number: prId,
            });

            const headSHA = getPullRequestResult.data.head.sha

            const getCheckSuitesResult = await github.rest.checks.listSuitesForRef({
              owner: repoOwner,
              repo: repoName,
              ref: headSHA,
            });

            console.log('result', getCheckSuitesResult.data)

            // console.log('context', context)
            // console.log('pr context', context.payload.issue.pull_request)
