name: Validate PR

on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]

jobs:
  validate-pr-title:
    runs-on: ubuntu-20.04
    if: ${{ !contains(github.event.pull_request.title, 'CN-') }}
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            console.log('context', context)
